# .golangci.yml
version: "2"
linters:
  enable:
    - gocyclo
    - gocognit
    - funlen
    - nestif
    - goconst # находит повторяющиеся строки

linters-settings:
  gocyclo:
    min-complexity: 35 # Стандарт 10-15. Если функция > 15, она делает слишком много.

  gocognit:
    min-complexity: 20 # Чуть мягче, чем cyclo, но наказывает за вложенность.

  funlen:
    lines: 80        # Жесткий лимит строк кода
    statements: 60   # Лимит инструкций

  nestif:
    min-complexity: 4 # Максимум 4 уровня вложенности if
